remove enchants on repair: true
disable anvil use: true
disable enchanting table use: true
disable items: [ENCHANTMENT_TABLE]
tool items: [ANVIL]
costs:
  1 gold:
    material: GOLD_INGOT
    amount: 1
  4 gold:
    material: GOLD_INGOT
    amount: 4
  3 gapple:
    material: GOLDEN_APPLE
    amount: 3
  5 gapple:
    material: GOLDEN_APPLE
    amount: 5
  1 obsidian:
    material: OBSIDIAN
    amount: 1
  4 obsidian:
    material: OBSIDIAN
    amount: 4
  glass bottle:
    material: GLASS_BOTTLE
    amount: 1
  5 feathers:
    material: FEATHER
    amount: 5
  slimeball:
    material: SLIME_BALL
    amount: 1
  slimeblock:
    material: SLIME_BLOCK
    amount: 1
  3 flint:
    material: FLINT
    amount: 3
  6 flint:
    material: FLINT
    amount: 6
  3 diamonds:
    material: DIAMOND
    amount: 3
  diamond block:
    material: DIAMOND_BLOCK
    amount: 1
  nether star:
    material: NETHER_STAR
    amount: 1
enchantments:
  PROTECTION_ENVIRONMENTAL:
    1: 1 gold
    2: 4 gold
    3: 4 obsidian
  PROTECTION_PROJECTILE:
    1: 1 gold
    2: 4 gold
    3: 4 obsidian
  OXYGEN:
    1: glass bottle
    2: glass bottle
    3: glass bottle
  PROTECTION_FALL:
    1: 5 feathers
    2: 5 feathers
    3: 5 feathers
  KNOCKBACK:
    1: slimeball
    2: slimeblock
  ARROW_KNOCKBACK:
    1: slimeball
    2: slimeblock
  DAMAGE_ALL:
    1: 3 flint
    2: 6 flint
    3: 3 diamonds
    4: diamond block
  ARROW_DAMAGE:
    1: 3 flint
    2: 6 flint
    3: 3 diamonds
    4: diamond block
  ARROW_FIRE:
    1: 5 gapple
  FIRE_ASPECT:
    1: 3 gapple
  ARROW_INFINITE:
    1: nether star
  DEPTH_STRIDER:
    1: 1 obsidian