name: PurchaseableEnchants
main: gg.uhc.purchaseableenchants.Entry
version: 1.0.0
author: ghowden/Eluinhost
database: false
depend: []
commands:
  enchcraft:
    description: Open enchant inventory
    usage: /enchcraft
permissions:
  uhc.deterministiccrafting.command:
    default: false